
server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: ToDoList-Backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: "file:./uploads/"

  mail:
    host: smtp.gmail.com
    port: 587
    username: yunusaouam22@gmail.com
    password: waiqxnmzefgmlmrr
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/jee_todolist_project
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  main:
    allow-circular-references: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE


